"""Make expiration_date nullable

Revision ID: 464bc016e462
Revises: 584eb3b822a8
Create Date: 2025-07-09 15:23:54.991283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464bc016e462'
down_revision = '584eb3b822a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
