"""Add avg_weight to InventoryItem

Revision ID: 4be9134a4a26
Revises: 464bc016e462
Create Date: 2025-07-12 16:23:33.380116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be9134a4a26'
down_revision = '464bc016e462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('avg_weight')

    # ### end Alembic commands ###
