"""Add title to RecipeRating

Revision ID: 4c52bd63237d
Revises: 75b3833a3ed2
Create Date: 2025-06-23 11:28:32.261417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c52bd63237d'
down_revision = '75b3833a3ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
