"""Add nutrition goals to User model

Revision ID: 584eb3b822a8
Revises: f738bfc0c1a4
Create Date: 2025-07-06 18:17:06.114473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584eb3b822a8'
down_revision = 'f738bfc0c1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_goal', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fat_goal')
        batch_op.drop_column('carbs_goal')
        batch_op.drop_column('protein_goal')
        batch_op.drop_column('calorie_goal')

    # ### end Alembic commands ###
