"""add nutrition columns to inventory_items

Revision ID: f02db8df8450
Revises: ec56bb01669a
Create Date: 2025-07-03 11:27:51.076663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02db8df8450'
down_revision = 'ec56bb01669a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('fat')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
