"""Switch recipe_id to recipe_hash

Revision ID: f738bfc0c1a4
Revises: 7ccc791b4f17
Create Date: 2025-07-06 17:34:56.322606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f738bfc0c1a4'
down_revision = '7ccc791b4f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_hash', sa.String(), nullable=False))
        batch_op.drop_constraint('nutrition_log_recipe_id_fkey', type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('nutrition_log_recipe_id_fkey', 'saved_recipes', ['recipe_id'], ['id'])
        batch_op.drop_column('recipe_hash')

    # ### end Alembic commands ###
